name: noaa-rss
channels:
  - viascience
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - fpdf=1.7.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.2.1
  - python=3.6.10
  - readline=8.0
  - setuptools=49.2.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

